#!/bin/bash                                                                                                                       LIST=$1
LOG_FILE=/opt/scripts/payb/ssl-check/ssl-check.log.tmp
CURRDATE=`date '+%s'`
echo $CURRDATE
echo `date -d@${CURRDATE}` > $LOG_FILE

while read LINE; do                                                                                                                                                       
        if echo | openssl s_client -servername $LINE -connect $LINE:443 >/dev/null ; 
		
		then                                                                                 
			SERTDATE=`echo | openssl s_client -servername $LINE -connect $LINE:443 2>/dev/null | openssl x509 -noout -enddate | cut -d '=' -f 2`
			SERTDATE_SEC=`date --date="${SERTDATE}" '+%s'`
			let "TIME = $SERTDATE_SEC - $CURRDATE"
			let "DELIM = $TIME / 86400" 
			echo -e "$DELIM days. ${LINE} $SERTDATE" >> $LOG_FILE
		else
			continue
		fi
done < $LIST

LOG=/opt/scripts/payb/ssl-check/ssl-check.log
cat $LOG_FILE | sort -n > $LOG
rm $LOG_FILE